title: Oddy Virgantara Putra Personal Web
description: > # this means to ignore newlines until "baseurl:"
  In here, you can find wonderful and absolutely free source code about PHP, Java, Python, R, and C++.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Oddy Virgantara Putra # add your name
author-img: oddy.jpg # add your photo
about-author: I am a researcher focusing on image processing, computer vision and machine learning particularly in visibility and color restoration in bad weather. # add description
social-twitter: # add your Twitter handle
social-facebook: # add your Facebook handle
social-github: virgantara # add your Github handle
social-linkedin: # add your Linkedin handle
social-email: # add your Email address

# Disqus
discus-identifier: virgantara # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
mathjax: true
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
